apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iks.intuit.com/managed: "false"
    iks.image-policy.k8s.io/allowed-registries: gcr.io,k8s.gcr.io,quay.io,docker.io,docker.intuit.com
  name: activemonitor-controller-sa
  namespace: health
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: activemonitor-controller-role
  namespace: health
rules:
- apiGroups:
  - "*"
  resources:
  - pods
  - deployments
  - replicasets
  - services
  - configmaps
  - secrets
  - workflows
  - serviceaccounts
  - roles
  - rolebindings
  verbs:
  - "*"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: activemonitor-controller-clusterrole
rules:
- apiGroups:
  - "*"
  - activemonitor.keikoproj.io
  resources:
  - workflows
  - monitors
  - pods
  - events
  - healthchecks
  - serviceaccounts
  - clusterroles
  - clusterrolebindings
  verbs:
  - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: activemonitor-controller-rb
  namespace: health
subjects:
- kind: ServiceAccount
  name: activemonitor-controller-sa
  namespace: health
roleRef:
  kind: Role
  name: activemonitor-controller-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: activemonitor-controller-cluster-rb
subjects:
- kind: ServiceAccount
  name: activemonitor-controller-sa
  namespace: health
roleRef:
  kind: ClusterRole
  name: activemonitor-controller-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemonitor-controller
  namespace: health
spec:
  replicas: 1
  selector:
    matchLabels:
      name: activemonitor-controller
  template:
    metadata:
      labels:
        name: activemonitor-controller
    spec:
      containers:
        - name: active-monitor
          image: keikoproj/active-monitor:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
              memory: "80Mi"
      serviceAccountName: activemonitor-controller-sa
